
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
#################################################
# file to edit: notebook.ipynb͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃

import time
from isolation import Board

# Credits if any͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
# 1)͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
# 2)͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
# 3)͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃

class OpenMoveEvalFn:
    def score(self, game, my_player=None):
        """Score the current game state
        Evaluation function that outputs a score equal to how many
        moves are open for AI player on the board minus how many moves
        are open for Opponent's player on the board.

        Note:
            If you think of better evaluation function, do it in CustomEvalFn below.

            Args
                game (Board): The board and game state.
                my_player (Player object): This specifies which player you are.

            Returns:
                float: The current state's score. MyMoves-OppMoves.

            """

        if game.__player_1__ == my_player:
            mmoves= game.get_player_moves(game.__player_1__)
            omoves=game.get_opponent_moves(game.__player_1__)

        if game.__player_2__ == my_player:
            mmoves= game.get_player_moves(game.__player_2__)
            omoves=game.get_opponent_moves(game.__player_2__)

        return (len(mmoves)-len(omoves))


        # TODO: finish this function!͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃


        #raise NotImplementedError


######################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
######################################################################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
################ END OF LOCAL TEST CODE SECTION ######################͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃

class CustomEvalFn:
    def __init__(self):
        pass

    def score(self, game, my_player=None):
        """Score the current game state.

        Custom evaluation function that acts however you think it should. This
        is not required but highly encouraged if you want to build the best
        AI possible.

        Args:
            game (Board): The board and game state.
            my_player (Player object): This specifies which player you are.

        Returns:
            float: The current state's score, based on your own heuristic.
        """
        if game.__player_1__ == my_player:
            mmoves= game.get_player_moves(game.__player_1__)
            omoves=game.get_opponent_moves(game.__player_1__)
            mpos= game.get_player_position(game.__player_1__)
            opos= game.get_player_position(game.__player_2__)



        if game.__player_2__ == my_player:
            mmoves= game.get_player_moves(game.__player_2__)
            omoves=game.get_opponent_moves(game.__player_2__)
            mpos= game.get_player_position(game.__player_2__)
            opos= game.get_player_position(game.__player_1__)



        scr=len(mmoves)-len(omoves)
        #md=8-(abs(mpos[0]-4)+abs(mpos[1]-4))
        dop=abs(mpos[0]-opos[0])+abs(mpos[1]-opos[1])

        #if game.move_count<5:
        #    return md

        return scr-0.25*(dop)



        # TODO: finish this function!͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃


        #raise NotImplementedError

######################################################################
############ DON'T WRITE ANY CODE OUTSIDE THE CLASS! #################͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
######################################################################

class CustomPlayer:
    # TODO: finish this class!͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
    """Player that chooses a move using your evaluation function
    and a minimax algorithm with alpha-beta pruning.
    You must finish and test this player to make sure it properly
    uses minimax and alpha-beta to return a good move."""

    def __init__(self, search_depth=6, eval_fn=OpenMoveEvalFn()):
        """Initializes your player.

        if you find yourself with a superior eval function, update the default
        value of `eval_fn` to `CustomEvalFn()`

        Args:
            search_depth (int): The depth to which your agent will search
            eval_fn (function): Evaluation function used by your agent
        """
        self.eval_fn = eval_fn
        self.search_depth = search_depth

    def move(self, game, time_left):
        """Called to determine one move by your agent

        Note:
            1. Do NOT change the name of this 'move' function. We are going to call
            this function directly.
            2. Call alphabeta instead of minimax once implemented.
        Args:
            game (Board): The board and game state.
            time_left (function): Used to determine time left before timeout

        Returns:
            tuple: (int,int): Your best move
        """
        #best_move, utility = alphabeta(self, game, time_left, depth=self.search_depth)
        #best_move, utility = minimax(self, game, time_left, depth=self.search_depth)


        #best_move, utility = alphabeta(self, game, time_left, depth=self.search_depth)

        #return best_move

        '''
        '''
        best_move=None
        best_val=float('-inf')
        depth=self.search_depth
        mordsi={}
        kmovesi={}


        for d in range(1,depth+1):

            t=time_left()
            if t <= 50:
                break
            bmove, utility, mordso= alphabeta(self, game, time_left, mordsi,d,float("-inf"), float("inf"), True)
            mordsi=mordso
            best_move=bmove
            best_val=utility
            t=time_left()
            if t <= 50:
                break

        return best_move




    def utility(self, game, my_turn):
        """You can handle special cases here (e.g. endgame)"""
        if my_turn:
            p=game.get_active_player()
        else:
            p=game.get_inactive_player()
        return self.eval_fn.score(game, p)



###################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE CLASS! ################͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
###### IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ###########͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
###################################################################


def minimax(player, game, time_left, depth, my_turn=True):
    """Implementation of the minimax algorithm.
    Args:
        player (CustomPlayer): This is the instantiation of CustomPlayer()
            that represents your agent. It is used to call anything you
            need from the CustomPlayer class (the utility() method, for example,
            or any class variables that belong to CustomPlayer()).
        game (Board): A board and game state.
        time_left (function): Used to determine time left before timeout
        depth: Used to track how deep you are in the search tree
        my_turn (bool): True if you are computing scores during your turn.

    Returns:
        (tuple, int): best_move, val
    """



    def max_val(gamest, depth):
        val=float('-inf')
        best_move= None
        mvs=gamest.get_active_moves()
        t=time_left()
        if depth == 0 or t<=10:
            val2=player.utility(gamest,True)
            return None, val2
        for m in mvs:
            newst, is_over, winner= gamest.forecast_move(m)
            if is_over:
                newval=player.utility(newst,False)
            else:
                _,newval=min_val(newst, depth-1)
            #print(f"{depth} Max eval move {m} utility {newval}")
            if newval > val:
                val=newval
                best_move=m
                #print(f"{depth} Max picked {best_move} val {val}")
        return best_move, val


    def min_val(gamest, depth):

        val=float('inf')
        best_move= None
        mvs=gamest.get_active_moves()
        t=time_left()
        if depth == 0 or t<=10:
            val2=player.utility(gamest,False)
            return None, val2
        for m in mvs:
            newst, is_over, winner= gamest.forecast_move(m)
            if is_over:
               newval=player.utility(newst,True)
            else :
                _,newval=max_val(newst, depth-1)
            #print(f"{depth} Min eval move {m} utility {newval}")
            if newval < val:
                val=newval
                best_move=m
                #print(f"{depth} Min picked {best_move} val {val}")
        return best_move, val


    if my_turn:
        return max_val(game,depth)
    else:
        return min_val(game,depth)





    # TODO: finish this function!͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃


    #raise NotImplementedError

######################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
######################################################################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
################ END OF LOCAL TEST CODE SECTION ######################͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃

def alphabeta(player, game, time_left, mords, depth, alpha=float("-inf"), beta=float("inf"), my_turn=True):
    """Implementation of the alphabeta algorithm.

    Args:
        player (CustomPlayer): This is the instantiation of CustomPlayer()
            that represents your agent. It is used to call anything you need
            from the CustomPlayer class (the utility() method, for example,
            or any class variables that belong to CustomPlayer())
        game (Board): A board and game state.
        time_left (function): Used to determine time left before timeout
        depth: Used to track how deep you are in the search tree
        alpha (float): Alpha value for pruning
        beta (float): Beta value for pruning
        my_turn (bool): True if you are computing scores during your turn.

    Returns:
        (tuple, int): best_move, val

    """
    indep=depth
    #print("indep "+str(indep))
    #print(mords)

    def qsearch(gamest,depth,a,b,mvs,ismax):
        scr=player.utility(gamest,ismax)
        if scr >=b:
            return scr
        elif a < scr:
            a=scr
        t=time_left()
        if depth==0 or not mvs or t<=30:
            return scr
        for m in mvs:
            newst, is_over, winner= gamest.forecast_move(m)
            if is_over:
                val=player.utility(newst,not ismax )
            else:
                nmvs=newst.get_active_moves()
                val=qsearch(newst,depth-1,a,b,nmvs,not ismax)
            if ismax:
                if val>=b:
                    return val
                if a < val:
                    a=val
            else:
                if a >=val:
                    return val
                if b > val:
                    b=val
        if ismax:
            return a
        else :
            return b



    def max_val(gamest, depth,a,b):
        val=float('-inf')
        best_move= None
        mvs=gamest.get_active_moves()
        t=time_left()
        if t<=50:
            #val2=player.utility(gamest,True)
            val2=qsearch(gamest,3,a,b,mvs,True)
            #val2=player.utility(gamest,True)
            return None, val2
        if depth == 0 :
            val2=qsearch(gamest,3,a,b,mvs,True)
            #val2=player.utility(gamest,True)
            return None, val2
        ind=indep-depth
        if ind not in mords.keys():
            mords[ind]={}
        omvs = sorted(mvs, key=lambda m: mords[ind].get(m, 0), reverse=True)
        #print(depth)
        #print(ind)
        #print(omvs)
        for m in omvs:
            newst, is_over, winner= gamest.forecast_move(m)
            if is_over:
                newval=player.utility(newst,False)
            else:
                _,newval=min_val(newst, depth-1,a,b)
            if m not in mords[ind].keys():
                mords[ind][m]=newval
            #print(f"{depth} Max eval move {m} utility {newval}")
            if newval > val:
                val=newval
                best_move=m
                #print(f"{depth} Max picked {best_move} val {val}")
            a=max(a,val)
            if val>=b:
                return best_move, val
        return best_move, val


    def min_val(gamest, depth,a,b):


        val=float('inf')
        best_move= None
        mvs=gamest.get_active_moves()
        t=time_left()
        if t<=50:
            #val2=player.utility(gamest,False)
            val2=qsearch(gamest,3,a,b,mvs,False)
            #val2=player.utility(gamest,True)
            return None, val2
        if depth == 0:
            val2=qsearch(gamest,3,a,b,mvs,False)
            #val2=player.utility(gamest,False)
            return None, val2
        ind=indep-depth
        if ind not in mords.keys():
            mords[ind]={}
        omvs = sorted(mvs, key=lambda m: mords[ind].get(m, 0))
        for m in omvs:
            newst, is_over, winner= gamest.forecast_move(m)
            if is_over:
               newval=player.utility(newst,True)
            else :
                _,newval=max_val(newst, depth-1,a,b)
            if m not in mords[ind].keys():
                mords[ind][m]=newval
            #print(f"{depth} Min eval move {m} utility {newval}")
            if newval < val:
                val=newval
                best_move=m
            b=min(b,val)
            if val<=a:
                return best_move, val
                #print(f"{depth} Min picked {best_move} val {val}")


        return best_move, val




    if my_turn:
        best_move, val=max_val(game,depth,alpha,beta)
        return best_move, val,mords
    else:
        best_move, val= min_val(game,depth,alpha,beta)
        return best_move, val ,mords

    # TODO: finish this function!͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃


    #raise NotImplementedError


######################################################################
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
######## IF YOU WANT TO CALL OR TEST IT CREATE A NEW CELL ############͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
######################################################################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
# tests.name_of_the_test #you can uncomment this line to run your test͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃
################ END OF LOCAL TEST CODE SECTION ######################͏︅͏︀͏︋͏︋͏󠄌͏󠄎͏︀͏󠄐͏󠄃͏︃